name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore ./LibraryUnitTest/LibraryUnitTest.sln # Adjust path if necessary

    - name: Build solution
      run: dotnet build ./LibraryUnitTest/LibraryUnitTest.sln --no-restore # Adjust path if necessary

    - name: Run tests
      run: dotnet test ./LibraryUnitTest/LibraryUnitTest.sln --no-build --verbosity normal # Adjust path if necessary
